// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: context_projection.sql

package db

import (
	"context"
	"database/sql"
)

const accountContextProjectionUsageAttempt = `-- name: AccountContextProjectionUsageAttempt :execrows
UPDATE context_projection_usage_attempts
SET accounted = 1,
    updated_at = ?1
WHERE node_id = ?2
  AND attempt_number = ?3
  AND session_id = ?4
  AND accounted = 0
`

type AccountContextProjectionUsageAttemptParams struct {
	UpdatedAt     int64  `json:"updated_at"`
	NodeID        string `json:"node_id"`
	AttemptNumber int64  `json:"attempt_number"`
	SessionID     string `json:"session_id"`
}

func (q *Queries) AccountContextProjectionUsageAttempt(ctx context.Context, arg AccountContextProjectionUsageAttemptParams) (int64, error) {
	result, err := q.exec(ctx, q.accountContextProjectionUsageAttemptStmt, accountContextProjectionUsageAttempt,
		arg.UpdatedAt,
		arg.NodeID,
		arg.AttemptNumber,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const activateContextProjectionClaim = `-- name: ActivateContextProjectionClaim :execrows
UPDATE context_projection_nodes
SET state = 'active',
    summary = ?1,
    projected_chars = ?2,
    lease_expires_at = NULL,
    claim_token = NULL,
    retry_after = NULL,
    failure = '',
    summarizer_provider = ?3,
    summarizer_model = ?4,
    prompt_tokens = ?5,
    completion_tokens = ?6,
    cost = ?7,
    updated_at = ?8
WHERE id = ?9
  AND session_id = ?10
  AND algorithm_version = ?11
  AND state = 'pending'
  AND claim_token = ?12
`

type ActivateContextProjectionClaimParams struct {
	Summary            string         `json:"summary"`
	ProjectedChars     int64          `json:"projected_chars"`
	SummarizerProvider string         `json:"summarizer_provider"`
	SummarizerModel    string         `json:"summarizer_model"`
	PromptTokens       int64          `json:"prompt_tokens"`
	CompletionTokens   int64          `json:"completion_tokens"`
	Cost               float64        `json:"cost"`
	UpdatedAt          int64          `json:"updated_at"`
	ID                 string         `json:"id"`
	SessionID          string         `json:"session_id"`
	AlgorithmVersion   int64          `json:"algorithm_version"`
	ClaimToken         sql.NullString `json:"claim_token"`
}

func (q *Queries) ActivateContextProjectionClaim(ctx context.Context, arg ActivateContextProjectionClaimParams) (int64, error) {
	result, err := q.exec(ctx, q.activateContextProjectionClaimStmt, activateContextProjectionClaim,
		arg.Summary,
		arg.ProjectedChars,
		arg.SummarizerProvider,
		arg.SummarizerModel,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
		arg.AlgorithmVersion,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countContextProjectionItemsBySession = `-- name: CountContextProjectionItemsBySession :one
SELECT count(*)
FROM context_projection_items
WHERE session_id = ?
`

func (q *Queries) CountContextProjectionItemsBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countContextProjectionItemsBySessionStmt, countContextProjectionItemsBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContextProjectionNodesBySession = `-- name: CountContextProjectionNodesBySession :one
SELECT count(*)
FROM context_projection_nodes
WHERE session_id = ?
`

func (q *Queries) CountContextProjectionNodesBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countContextProjectionNodesBySessionStmt, countContextProjectionNodesBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContextProjectionSourcesBySession = `-- name: CountContextProjectionSourcesBySession :one
SELECT count(*)
FROM context_projection_sources
WHERE session_id = ?
`

func (q *Queries) CountContextProjectionSourcesBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countContextProjectionSourcesBySessionStmt, countContextProjectionSourcesBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContextProjectionUsageAttemptsBySession = `-- name: CountContextProjectionUsageAttemptsBySession :one
SELECT count(*)
FROM context_projection_usage_attempts
WHERE session_id = ?
`

func (q *Queries) CountContextProjectionUsageAttemptsBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countContextProjectionUsageAttemptsBySessionStmt, countContextProjectionUsageAttemptsBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContextProjectionClaim = `-- name: CreateContextProjectionClaim :one
INSERT INTO context_projection_nodes (
    id,
    session_id,
    batch_key,
    source_hash,
    algorithm_version,
    configuration_id,
    state,
    first_message_id,
    last_message_id,
    raw_chars,
    lease_expires_at,
    claim_token,
    attempt_count,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, 'pending', ?, ?, ?, ?, ?, 1, ?, ?
)
ON CONFLICT (session_id, batch_key, source_hash, algorithm_version, configuration_id) DO NOTHING
RETURNING id, session_id, batch_key, source_hash, algorithm_version, configuration_id, state, summary, first_message_id, last_message_id, raw_chars, projected_chars, lease_expires_at, claim_token, attempt_count, retry_after, failure, summarizer_provider, summarizer_model, prompt_tokens, completion_tokens, cost, created_at, updated_at
`

type CreateContextProjectionClaimParams struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	BatchKey         string         `json:"batch_key"`
	SourceHash       string         `json:"source_hash"`
	AlgorithmVersion int64          `json:"algorithm_version"`
	ConfigurationID  string         `json:"configuration_id"`
	FirstMessageID   string         `json:"first_message_id"`
	LastMessageID    string         `json:"last_message_id"`
	RawChars         int64          `json:"raw_chars"`
	LeaseExpiresAt   sql.NullInt64  `json:"lease_expires_at"`
	ClaimToken       sql.NullString `json:"claim_token"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) CreateContextProjectionClaim(ctx context.Context, arg CreateContextProjectionClaimParams) (ContextProjectionNode, error) {
	row := q.queryRow(ctx, q.createContextProjectionClaimStmt, createContextProjectionClaim,
		arg.ID,
		arg.SessionID,
		arg.BatchKey,
		arg.SourceHash,
		arg.AlgorithmVersion,
		arg.ConfigurationID,
		arg.FirstMessageID,
		arg.LastMessageID,
		arg.RawChars,
		arg.LeaseExpiresAt,
		arg.ClaimToken,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ContextProjectionNode
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BatchKey,
		&i.SourceHash,
		&i.AlgorithmVersion,
		&i.ConfigurationID,
		&i.State,
		&i.Summary,
		&i.FirstMessageID,
		&i.LastMessageID,
		&i.RawChars,
		&i.ProjectedChars,
		&i.LeaseExpiresAt,
		&i.ClaimToken,
		&i.AttemptCount,
		&i.RetryAfter,
		&i.Failure,
		&i.SummarizerProvider,
		&i.SummarizerModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContextProjectionItem = `-- name: CreateContextProjectionItem :exec
INSERT INTO context_projection_items (
    id,
    node_id,
    session_id,
    source_message_id,
    source_part_ordinal,
    tool_call_id,
    tool_name,
    description,
    ref_number,
    source_hash,
    ordinal,
    algorithm_version
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateContextProjectionItemParams struct {
	ID                string `json:"id"`
	NodeID            string `json:"node_id"`
	SessionID         string `json:"session_id"`
	SourceMessageID   string `json:"source_message_id"`
	SourcePartOrdinal int64  `json:"source_part_ordinal"`
	ToolCallID        string `json:"tool_call_id"`
	ToolName          string `json:"tool_name"`
	Description       string `json:"description"`
	RefNumber         int64  `json:"ref_number"`
	SourceHash        string `json:"source_hash"`
	Ordinal           int64  `json:"ordinal"`
	AlgorithmVersion  int64  `json:"algorithm_version"`
}

func (q *Queries) CreateContextProjectionItem(ctx context.Context, arg CreateContextProjectionItemParams) error {
	_, err := q.exec(ctx, q.createContextProjectionItemStmt, createContextProjectionItem,
		arg.ID,
		arg.NodeID,
		arg.SessionID,
		arg.SourceMessageID,
		arg.SourcePartOrdinal,
		arg.ToolCallID,
		arg.ToolName,
		arg.Description,
		arg.RefNumber,
		arg.SourceHash,
		arg.Ordinal,
		arg.AlgorithmVersion,
	)
	return err
}

const createContextProjectionSource = `-- name: CreateContextProjectionSource :exec
INSERT INTO context_projection_sources (
    node_id,
    session_id,
    source_message_id,
    source_part_ordinal,
    part_kind,
    source_hash,
    ordinal
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateContextProjectionSourceParams struct {
	NodeID            string `json:"node_id"`
	SessionID         string `json:"session_id"`
	SourceMessageID   string `json:"source_message_id"`
	SourcePartOrdinal int64  `json:"source_part_ordinal"`
	PartKind          string `json:"part_kind"`
	SourceHash        string `json:"source_hash"`
	Ordinal           int64  `json:"ordinal"`
}

func (q *Queries) CreateContextProjectionSource(ctx context.Context, arg CreateContextProjectionSourceParams) error {
	_, err := q.exec(ctx, q.createContextProjectionSourceStmt, createContextProjectionSource,
		arg.NodeID,
		arg.SessionID,
		arg.SourceMessageID,
		arg.SourcePartOrdinal,
		arg.PartKind,
		arg.SourceHash,
		arg.Ordinal,
	)
	return err
}

const createContextProjectionUsageAttempt = `-- name: CreateContextProjectionUsageAttempt :exec
INSERT INTO context_projection_usage_attempts (
    node_id,
    session_id,
    attempt_number,
    summarizer_provider,
    summarizer_model,
    prompt_tokens,
    completion_tokens,
    cost,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateContextProjectionUsageAttemptParams struct {
	NodeID             string  `json:"node_id"`
	SessionID          string  `json:"session_id"`
	AttemptNumber      int64   `json:"attempt_number"`
	SummarizerProvider string  `json:"summarizer_provider"`
	SummarizerModel    string  `json:"summarizer_model"`
	PromptTokens       int64   `json:"prompt_tokens"`
	CompletionTokens   int64   `json:"completion_tokens"`
	Cost               float64 `json:"cost"`
	CreatedAt          int64   `json:"created_at"`
	UpdatedAt          int64   `json:"updated_at"`
}

func (q *Queries) CreateContextProjectionUsageAttempt(ctx context.Context, arg CreateContextProjectionUsageAttemptParams) error {
	_, err := q.exec(ctx, q.createContextProjectionUsageAttemptStmt, createContextProjectionUsageAttempt,
		arg.NodeID,
		arg.SessionID,
		arg.AttemptNumber,
		arg.SummarizerProvider,
		arg.SummarizerModel,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteContextProjectionItemsByNode = `-- name: DeleteContextProjectionItemsByNode :exec
DELETE FROM context_projection_items
WHERE node_id = ?
`

func (q *Queries) DeleteContextProjectionItemsByNode(ctx context.Context, nodeID string) error {
	_, err := q.exec(ctx, q.deleteContextProjectionItemsByNodeStmt, deleteContextProjectionItemsByNode, nodeID)
	return err
}

const deleteContextProjectionSourcesByNode = `-- name: DeleteContextProjectionSourcesByNode :exec
DELETE FROM context_projection_sources
WHERE node_id = ?
`

func (q *Queries) DeleteContextProjectionSourcesByNode(ctx context.Context, nodeID string) error {
	_, err := q.exec(ctx, q.deleteContextProjectionSourcesByNodeStmt, deleteContextProjectionSourcesByNode, nodeID)
	return err
}

const failContextProjectionClaim = `-- name: FailContextProjectionClaim :execrows
UPDATE context_projection_nodes
SET state = 'failed',
    lease_expires_at = NULL,
    claim_token = NULL,
    retry_after = ?1,
    failure = ?2,
    summarizer_provider = ?3,
    summarizer_model = ?4,
    prompt_tokens = ?5,
    completion_tokens = ?6,
    cost = ?7,
    updated_at = ?8
WHERE id = ?9
  AND session_id = ?10
  AND algorithm_version = ?11
  AND state = 'pending'
  AND claim_token = ?12
`

type FailContextProjectionClaimParams struct {
	RetryAfter         sql.NullInt64  `json:"retry_after"`
	Failure            string         `json:"failure"`
	SummarizerProvider string         `json:"summarizer_provider"`
	SummarizerModel    string         `json:"summarizer_model"`
	PromptTokens       int64          `json:"prompt_tokens"`
	CompletionTokens   int64          `json:"completion_tokens"`
	Cost               float64        `json:"cost"`
	UpdatedAt          int64          `json:"updated_at"`
	ID                 string         `json:"id"`
	SessionID          string         `json:"session_id"`
	AlgorithmVersion   int64          `json:"algorithm_version"`
	ClaimToken         sql.NullString `json:"claim_token"`
}

func (q *Queries) FailContextProjectionClaim(ctx context.Context, arg FailContextProjectionClaimParams) (int64, error) {
	result, err := q.exec(ctx, q.failContextProjectionClaimStmt, failContextProjectionClaim,
		arg.RetryAfter,
		arg.Failure,
		arg.SummarizerProvider,
		arg.SummarizerModel,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
		arg.AlgorithmVersion,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveContextProjectionItemByRef = `-- name: GetActiveContextProjectionItemByRef :one
SELECT
    i.id,
    i.node_id,
    i.session_id,
    i.source_message_id,
    i.source_part_ordinal,
    i.tool_call_id,
    i.tool_name,
    i.description,
    i.ref_number,
    i.source_hash,
    i.ordinal,
    i.algorithm_version
FROM context_projection_items AS i
JOIN context_projection_nodes AS n
  ON n.id = i.node_id
 AND n.session_id = i.session_id
 AND n.algorithm_version = i.algorithm_version
WHERE i.session_id = ?
  AND i.ref_number = ?
  AND n.state = 'active'
LIMIT 1
`

type GetActiveContextProjectionItemByRefParams struct {
	SessionID string `json:"session_id"`
	RefNumber int64  `json:"ref_number"`
}

func (q *Queries) GetActiveContextProjectionItemByRef(ctx context.Context, arg GetActiveContextProjectionItemByRefParams) (ContextProjectionItem, error) {
	row := q.queryRow(ctx, q.getActiveContextProjectionItemByRefStmt, getActiveContextProjectionItemByRef, arg.SessionID, arg.RefNumber)
	var i ContextProjectionItem
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SessionID,
		&i.SourceMessageID,
		&i.SourcePartOrdinal,
		&i.ToolCallID,
		&i.ToolName,
		&i.Description,
		&i.RefNumber,
		&i.SourceHash,
		&i.Ordinal,
		&i.AlgorithmVersion,
	)
	return i, err
}

const getActiveContextProjectionNodeForSource = `-- name: GetActiveContextProjectionNodeForSource :one
SELECT id, session_id, batch_key, source_hash, algorithm_version, configuration_id, state, summary, first_message_id, last_message_id, raw_chars, projected_chars, lease_expires_at, claim_token, attempt_count, retry_after, failure, summarizer_provider, summarizer_model, prompt_tokens, completion_tokens, cost, created_at, updated_at
FROM context_projection_nodes
WHERE session_id = ?
  AND batch_key = ?
  AND source_hash = ?
  AND algorithm_version = ?
  AND state = 'active'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetActiveContextProjectionNodeForSourceParams struct {
	SessionID        string `json:"session_id"`
	BatchKey         string `json:"batch_key"`
	SourceHash       string `json:"source_hash"`
	AlgorithmVersion int64  `json:"algorithm_version"`
}

func (q *Queries) GetActiveContextProjectionNodeForSource(ctx context.Context, arg GetActiveContextProjectionNodeForSourceParams) (ContextProjectionNode, error) {
	row := q.queryRow(ctx, q.getActiveContextProjectionNodeForSourceStmt, getActiveContextProjectionNodeForSource,
		arg.SessionID,
		arg.BatchKey,
		arg.SourceHash,
		arg.AlgorithmVersion,
	)
	var i ContextProjectionNode
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BatchKey,
		&i.SourceHash,
		&i.AlgorithmVersion,
		&i.ConfigurationID,
		&i.State,
		&i.Summary,
		&i.FirstMessageID,
		&i.LastMessageID,
		&i.RawChars,
		&i.ProjectedChars,
		&i.LeaseExpiresAt,
		&i.ClaimToken,
		&i.AttemptCount,
		&i.RetryAfter,
		&i.Failure,
		&i.SummarizerProvider,
		&i.SummarizerModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContextProjectionClaim = `-- name: GetContextProjectionClaim :one
SELECT id, session_id, batch_key, source_hash, algorithm_version, configuration_id, state, summary, first_message_id, last_message_id, raw_chars, projected_chars, lease_expires_at, claim_token, attempt_count, retry_after, failure, summarizer_provider, summarizer_model, prompt_tokens, completion_tokens, cost, created_at, updated_at
FROM context_projection_nodes
WHERE id = ?
  AND session_id = ?
  AND algorithm_version = ?
  AND state = 'pending'
  AND claim_token = ?
LIMIT 1
`

type GetContextProjectionClaimParams struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	AlgorithmVersion int64          `json:"algorithm_version"`
	ClaimToken       sql.NullString `json:"claim_token"`
}

func (q *Queries) GetContextProjectionClaim(ctx context.Context, arg GetContextProjectionClaimParams) (ContextProjectionNode, error) {
	row := q.queryRow(ctx, q.getContextProjectionClaimStmt, getContextProjectionClaim,
		arg.ID,
		arg.SessionID,
		arg.AlgorithmVersion,
		arg.ClaimToken,
	)
	var i ContextProjectionNode
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BatchKey,
		&i.SourceHash,
		&i.AlgorithmVersion,
		&i.ConfigurationID,
		&i.State,
		&i.Summary,
		&i.FirstMessageID,
		&i.LastMessageID,
		&i.RawChars,
		&i.ProjectedChars,
		&i.LeaseExpiresAt,
		&i.ClaimToken,
		&i.AttemptCount,
		&i.RetryAfter,
		&i.Failure,
		&i.SummarizerProvider,
		&i.SummarizerModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContextProjectionNode = `-- name: GetContextProjectionNode :one
SELECT id, session_id, batch_key, source_hash, algorithm_version, configuration_id, state, summary, first_message_id, last_message_id, raw_chars, projected_chars, lease_expires_at, claim_token, attempt_count, retry_after, failure, summarizer_provider, summarizer_model, prompt_tokens, completion_tokens, cost, created_at, updated_at
FROM context_projection_nodes
WHERE session_id = ?
  AND batch_key = ?
  AND source_hash = ?
  AND algorithm_version = ?
  AND configuration_id = ?
LIMIT 1
`

type GetContextProjectionNodeParams struct {
	SessionID        string `json:"session_id"`
	BatchKey         string `json:"batch_key"`
	SourceHash       string `json:"source_hash"`
	AlgorithmVersion int64  `json:"algorithm_version"`
	ConfigurationID  string `json:"configuration_id"`
}

func (q *Queries) GetContextProjectionNode(ctx context.Context, arg GetContextProjectionNodeParams) (ContextProjectionNode, error) {
	row := q.queryRow(ctx, q.getContextProjectionNodeStmt, getContextProjectionNode,
		arg.SessionID,
		arg.BatchKey,
		arg.SourceHash,
		arg.AlgorithmVersion,
		arg.ConfigurationID,
	)
	var i ContextProjectionNode
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BatchKey,
		&i.SourceHash,
		&i.AlgorithmVersion,
		&i.ConfigurationID,
		&i.State,
		&i.Summary,
		&i.FirstMessageID,
		&i.LastMessageID,
		&i.RawChars,
		&i.ProjectedChars,
		&i.LeaseExpiresAt,
		&i.ClaimToken,
		&i.AttemptCount,
		&i.RetryAfter,
		&i.Failure,
		&i.SummarizerProvider,
		&i.SummarizerModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContextProjectionNodeForSource = `-- name: GetContextProjectionNodeForSource :one
SELECT id, session_id, batch_key, source_hash, algorithm_version, configuration_id, state, summary, first_message_id, last_message_id, raw_chars, projected_chars, lease_expires_at, claim_token, attempt_count, retry_after, failure, summarizer_provider, summarizer_model, prompt_tokens, completion_tokens, cost, created_at, updated_at
FROM context_projection_nodes
WHERE session_id = ?
  AND batch_key = ?
  AND source_hash = ?
  AND algorithm_version = ?
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetContextProjectionNodeForSourceParams struct {
	SessionID        string `json:"session_id"`
	BatchKey         string `json:"batch_key"`
	SourceHash       string `json:"source_hash"`
	AlgorithmVersion int64  `json:"algorithm_version"`
}

func (q *Queries) GetContextProjectionNodeForSource(ctx context.Context, arg GetContextProjectionNodeForSourceParams) (ContextProjectionNode, error) {
	row := q.queryRow(ctx, q.getContextProjectionNodeForSourceStmt, getContextProjectionNodeForSource,
		arg.SessionID,
		arg.BatchKey,
		arg.SourceHash,
		arg.AlgorithmVersion,
	)
	var i ContextProjectionNode
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BatchKey,
		&i.SourceHash,
		&i.AlgorithmVersion,
		&i.ConfigurationID,
		&i.State,
		&i.Summary,
		&i.FirstMessageID,
		&i.LastMessageID,
		&i.RawChars,
		&i.ProjectedChars,
		&i.LeaseExpiresAt,
		&i.ClaimToken,
		&i.AttemptCount,
		&i.RetryAfter,
		&i.Failure,
		&i.SummarizerProvider,
		&i.SummarizerModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContextProjectionRefCounter = `-- name: GetContextProjectionRefCounter :one
SELECT next_ref_number
FROM context_projection_ref_counter
WHERE singleton = 1
`

func (q *Queries) GetContextProjectionRefCounter(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getContextProjectionRefCounterStmt, getContextProjectionRefCounter)
	var next_ref_number int64
	err := row.Scan(&next_ref_number)
	return next_ref_number, err
}

const listActiveContextProjectionNodes = `-- name: ListActiveContextProjectionNodes :many
SELECT id, session_id, batch_key, source_hash, algorithm_version, configuration_id, state, summary, first_message_id, last_message_id, raw_chars, projected_chars, lease_expires_at, claim_token, attempt_count, retry_after, failure, summarizer_provider, summarizer_model, prompt_tokens, completion_tokens, cost, created_at, updated_at
FROM context_projection_nodes
WHERE session_id = ?
  AND algorithm_version = ?
  AND state = 'active'
ORDER BY created_at ASC, id ASC
`

type ListActiveContextProjectionNodesParams struct {
	SessionID        string `json:"session_id"`
	AlgorithmVersion int64  `json:"algorithm_version"`
}

func (q *Queries) ListActiveContextProjectionNodes(ctx context.Context, arg ListActiveContextProjectionNodesParams) ([]ContextProjectionNode, error) {
	rows, err := q.query(ctx, q.listActiveContextProjectionNodesStmt, listActiveContextProjectionNodes, arg.SessionID, arg.AlgorithmVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextProjectionNode{}
	for rows.Next() {
		var i ContextProjectionNode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.BatchKey,
			&i.SourceHash,
			&i.AlgorithmVersion,
			&i.ConfigurationID,
			&i.State,
			&i.Summary,
			&i.FirstMessageID,
			&i.LastMessageID,
			&i.RawChars,
			&i.ProjectedChars,
			&i.LeaseExpiresAt,
			&i.ClaimToken,
			&i.AttemptCount,
			&i.RetryAfter,
			&i.Failure,
			&i.SummarizerProvider,
			&i.SummarizerModel,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveContextProjectionNodesBySourceMessage = `-- name: ListActiveContextProjectionNodesBySourceMessage :many
SELECT DISTINCT n.id, n.session_id, n.batch_key, n.source_hash, n.algorithm_version, n.configuration_id, n.state, n.summary, n.first_message_id, n.last_message_id, n.raw_chars, n.projected_chars, n.lease_expires_at, n.claim_token, n.attempt_count, n.retry_after, n.failure, n.summarizer_provider, n.summarizer_model, n.prompt_tokens, n.completion_tokens, n.cost, n.created_at, n.updated_at
FROM context_projection_nodes AS n
JOIN context_projection_sources AS s
  ON s.node_id = n.id
 AND s.session_id = n.session_id
WHERE n.state = 'active'
  AND s.session_id = ?1
  AND s.source_message_id = ?2
ORDER BY n.created_at ASC, n.id ASC
`

type ListActiveContextProjectionNodesBySourceMessageParams struct {
	SessionID       string `json:"session_id"`
	SourceMessageID string `json:"source_message_id"`
}

func (q *Queries) ListActiveContextProjectionNodesBySourceMessage(ctx context.Context, arg ListActiveContextProjectionNodesBySourceMessageParams) ([]ContextProjectionNode, error) {
	rows, err := q.query(ctx, q.listActiveContextProjectionNodesBySourceMessageStmt, listActiveContextProjectionNodesBySourceMessage, arg.SessionID, arg.SourceMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextProjectionNode{}
	for rows.Next() {
		var i ContextProjectionNode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.BatchKey,
			&i.SourceHash,
			&i.AlgorithmVersion,
			&i.ConfigurationID,
			&i.State,
			&i.Summary,
			&i.FirstMessageID,
			&i.LastMessageID,
			&i.RawChars,
			&i.ProjectedChars,
			&i.LeaseExpiresAt,
			&i.ClaimToken,
			&i.AttemptCount,
			&i.RetryAfter,
			&i.Failure,
			&i.SummarizerProvider,
			&i.SummarizerModel,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveContextProjectionNodesBySession = `-- name: ListAllActiveContextProjectionNodesBySession :many
SELECT id, session_id, batch_key, source_hash, algorithm_version, configuration_id, state, summary, first_message_id, last_message_id, raw_chars, projected_chars, lease_expires_at, claim_token, attempt_count, retry_after, failure, summarizer_provider, summarizer_model, prompt_tokens, completion_tokens, cost, created_at, updated_at
FROM context_projection_nodes
WHERE session_id = ?
  AND state = 'active'
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListAllActiveContextProjectionNodesBySession(ctx context.Context, sessionID string) ([]ContextProjectionNode, error) {
	rows, err := q.query(ctx, q.listAllActiveContextProjectionNodesBySessionStmt, listAllActiveContextProjectionNodesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextProjectionNode{}
	for rows.Next() {
		var i ContextProjectionNode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.BatchKey,
			&i.SourceHash,
			&i.AlgorithmVersion,
			&i.ConfigurationID,
			&i.State,
			&i.Summary,
			&i.FirstMessageID,
			&i.LastMessageID,
			&i.RawChars,
			&i.ProjectedChars,
			&i.LeaseExpiresAt,
			&i.ClaimToken,
			&i.AttemptCount,
			&i.RetryAfter,
			&i.Failure,
			&i.SummarizerProvider,
			&i.SummarizerModel,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCanonicalContextProjectionMessages = `-- name: ListCanonicalContextProjectionMessages :many
SELECT m.id, m.session_id, m.role, m.parts, m.model, m.created_at, m.updated_at, m.finished_at, m.provider, m.is_summary_message
FROM messages AS m
WHERE m.session_id = ?
ORDER BY m.created_at ASC, m.rowid ASC
`

func (q *Queries) ListCanonicalContextProjectionMessages(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listCanonicalContextProjectionMessagesStmt, listCanonicalContextProjectionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConflictingActiveContextProjectionNodes = `-- name: ListConflictingActiveContextProjectionNodes :many
SELECT DISTINCT n.id, n.session_id, n.batch_key, n.source_hash, n.algorithm_version, n.configuration_id, n.state, n.summary, n.first_message_id, n.last_message_id, n.raw_chars, n.projected_chars, n.lease_expires_at, n.claim_token, n.attempt_count, n.retry_after, n.failure, n.summarizer_provider, n.summarizer_model, n.prompt_tokens, n.completion_tokens, n.cost, n.created_at, n.updated_at
FROM context_projection_nodes AS n
JOIN context_projection_items AS i
  ON i.node_id = n.id
 AND i.session_id = n.session_id
 AND i.algorithm_version = n.algorithm_version
WHERE n.session_id = ?1
  AND n.algorithm_version = ?2
  AND n.state = 'active'
  AND i.source_message_id = ?3
  AND i.source_part_ordinal = ?4
ORDER BY n.created_at ASC, n.id ASC
`

type ListConflictingActiveContextProjectionNodesParams struct {
	SessionID         string `json:"session_id"`
	AlgorithmVersion  int64  `json:"algorithm_version"`
	SourceMessageID   string `json:"source_message_id"`
	SourcePartOrdinal int64  `json:"source_part_ordinal"`
}

func (q *Queries) ListConflictingActiveContextProjectionNodes(ctx context.Context, arg ListConflictingActiveContextProjectionNodesParams) ([]ContextProjectionNode, error) {
	rows, err := q.query(ctx, q.listConflictingActiveContextProjectionNodesStmt, listConflictingActiveContextProjectionNodes,
		arg.SessionID,
		arg.AlgorithmVersion,
		arg.SourceMessageID,
		arg.SourcePartOrdinal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextProjectionNode{}
	for rows.Next() {
		var i ContextProjectionNode
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.BatchKey,
			&i.SourceHash,
			&i.AlgorithmVersion,
			&i.ConfigurationID,
			&i.State,
			&i.Summary,
			&i.FirstMessageID,
			&i.LastMessageID,
			&i.RawChars,
			&i.ProjectedChars,
			&i.LeaseExpiresAt,
			&i.ClaimToken,
			&i.AttemptCount,
			&i.RetryAfter,
			&i.Failure,
			&i.SummarizerProvider,
			&i.SummarizerModel,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContextProjectionItemsByNode = `-- name: ListContextProjectionItemsByNode :many
SELECT id, node_id, session_id, source_message_id, source_part_ordinal, tool_call_id, tool_name, description, ref_number, source_hash, ordinal, algorithm_version
FROM context_projection_items
WHERE node_id = ?
ORDER BY ordinal ASC
`

func (q *Queries) ListContextProjectionItemsByNode(ctx context.Context, nodeID string) ([]ContextProjectionItem, error) {
	rows, err := q.query(ctx, q.listContextProjectionItemsByNodeStmt, listContextProjectionItemsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextProjectionItem{}
	for rows.Next() {
		var i ContextProjectionItem
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.SessionID,
			&i.SourceMessageID,
			&i.SourcePartOrdinal,
			&i.ToolCallID,
			&i.ToolName,
			&i.Description,
			&i.RefNumber,
			&i.SourceHash,
			&i.Ordinal,
			&i.AlgorithmVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContextProjectionSourcesByNode = `-- name: ListContextProjectionSourcesByNode :many
SELECT node_id, session_id, source_message_id, source_part_ordinal, part_kind, source_hash, ordinal
FROM context_projection_sources
WHERE node_id = ?
ORDER BY ordinal ASC
`

func (q *Queries) ListContextProjectionSourcesByNode(ctx context.Context, nodeID string) ([]ContextProjectionSource, error) {
	rows, err := q.query(ctx, q.listContextProjectionSourcesByNodeStmt, listContextProjectionSourcesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextProjectionSource{}
	for rows.Next() {
		var i ContextProjectionSource
		if err := rows.Scan(
			&i.NodeID,
			&i.SessionID,
			&i.SourceMessageID,
			&i.SourcePartOrdinal,
			&i.PartKind,
			&i.SourceHash,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnaccountedContextProjectionUsage = `-- name: ListUnaccountedContextProjectionUsage :many
SELECT node_id, session_id, attempt_number, summarizer_provider, summarizer_model, prompt_tokens, completion_tokens, cost, accounted, created_at, updated_at
FROM context_projection_usage_attempts
WHERE session_id = ?
  AND accounted = 0
ORDER BY created_at ASC, node_id ASC, attempt_number ASC
`

func (q *Queries) ListUnaccountedContextProjectionUsage(ctx context.Context, sessionID string) ([]ContextProjectionUsageAttempt, error) {
	rows, err := q.query(ctx, q.listUnaccountedContextProjectionUsageStmt, listUnaccountedContextProjectionUsage, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextProjectionUsageAttempt{}
	for rows.Next() {
		var i ContextProjectionUsageAttempt
		if err := rows.Scan(
			&i.NodeID,
			&i.SessionID,
			&i.AttemptNumber,
			&i.SummarizerProvider,
			&i.SummarizerModel,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.Accounted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclaimContextProjectionClaim = `-- name: ReclaimContextProjectionClaim :one
UPDATE context_projection_nodes
SET state = 'pending',
    lease_expires_at = ?1,
    claim_token = ?2,
    attempt_count = attempt_count + 1,
    retry_after = NULL,
    failure = '',
    summarizer_provider = '',
    summarizer_model = '',
    prompt_tokens = 0,
    completion_tokens = 0,
    cost = 0,
    updated_at = ?3
WHERE session_id = ?4
  AND batch_key = ?5
  AND source_hash = ?6
  AND algorithm_version = ?7
  AND configuration_id = ?8
  AND (
      state = 'stale'
      OR
      (state = 'pending' AND lease_expires_at <= ?9)
      OR
      (state = 'failed' AND retry_after IS NOT NULL AND retry_after <= ?9)
  )
RETURNING id, session_id, batch_key, source_hash, algorithm_version, configuration_id, state, summary, first_message_id, last_message_id, raw_chars, projected_chars, lease_expires_at, claim_token, attempt_count, retry_after, failure, summarizer_provider, summarizer_model, prompt_tokens, completion_tokens, cost, created_at, updated_at
`

type ReclaimContextProjectionClaimParams struct {
	LeaseExpiresAt   sql.NullInt64  `json:"lease_expires_at"`
	ClaimToken       sql.NullString `json:"claim_token"`
	UpdatedAt        int64          `json:"updated_at"`
	SessionID        string         `json:"session_id"`
	BatchKey         string         `json:"batch_key"`
	SourceHash       string         `json:"source_hash"`
	AlgorithmVersion int64          `json:"algorithm_version"`
	ConfigurationID  string         `json:"configuration_id"`
	Now              sql.NullInt64  `json:"now"`
}

func (q *Queries) ReclaimContextProjectionClaim(ctx context.Context, arg ReclaimContextProjectionClaimParams) (ContextProjectionNode, error) {
	row := q.queryRow(ctx, q.reclaimContextProjectionClaimStmt, reclaimContextProjectionClaim,
		arg.LeaseExpiresAt,
		arg.ClaimToken,
		arg.UpdatedAt,
		arg.SessionID,
		arg.BatchKey,
		arg.SourceHash,
		arg.AlgorithmVersion,
		arg.ConfigurationID,
		arg.Now,
	)
	var i ContextProjectionNode
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BatchKey,
		&i.SourceHash,
		&i.AlgorithmVersion,
		&i.ConfigurationID,
		&i.State,
		&i.Summary,
		&i.FirstMessageID,
		&i.LastMessageID,
		&i.RawChars,
		&i.ProjectedChars,
		&i.LeaseExpiresAt,
		&i.ClaimToken,
		&i.AttemptCount,
		&i.RetryAfter,
		&i.Failure,
		&i.SummarizerProvider,
		&i.SummarizerModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveContextProjectionRefs = `-- name: ReserveContextProjectionRefs :one
UPDATE context_projection_ref_counter
SET next_ref_number = next_ref_number + ?1
WHERE singleton = 1
  AND ?1 > 0
  AND next_ref_number <= 9223372036854775807 - ?1
RETURNING next_ref_number - ?1
`

func (q *Queries) ReserveContextProjectionRefs(ctx context.Context, count int64) (int64, error) {
	row := q.queryRow(ctx, q.reserveContextProjectionRefsStmt, reserveContextProjectionRefs, count)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const skipContextProjectionClaim = `-- name: SkipContextProjectionClaim :execrows
UPDATE context_projection_nodes
SET state = 'skipped',
    lease_expires_at = NULL,
    claim_token = NULL,
    retry_after = NULL,
    failure = ?1,
    summarizer_provider = ?2,
    summarizer_model = ?3,
    prompt_tokens = ?4,
    completion_tokens = ?5,
    cost = ?6,
    updated_at = ?7
WHERE id = ?8
  AND session_id = ?9
  AND algorithm_version = ?10
  AND state = 'pending'
  AND claim_token = ?11
`

type SkipContextProjectionClaimParams struct {
	Failure            string         `json:"failure"`
	SummarizerProvider string         `json:"summarizer_provider"`
	SummarizerModel    string         `json:"summarizer_model"`
	PromptTokens       int64          `json:"prompt_tokens"`
	CompletionTokens   int64          `json:"completion_tokens"`
	Cost               float64        `json:"cost"`
	UpdatedAt          int64          `json:"updated_at"`
	ID                 string         `json:"id"`
	SessionID          string         `json:"session_id"`
	AlgorithmVersion   int64          `json:"algorithm_version"`
	ClaimToken         sql.NullString `json:"claim_token"`
}

func (q *Queries) SkipContextProjectionClaim(ctx context.Context, arg SkipContextProjectionClaimParams) (int64, error) {
	result, err := q.exec(ctx, q.skipContextProjectionClaimStmt, skipContextProjectionClaim,
		arg.Failure,
		arg.SummarizerProvider,
		arg.SummarizerModel,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
		arg.AlgorithmVersion,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const staleActiveContextProjectionNode = `-- name: StaleActiveContextProjectionNode :execrows
UPDATE context_projection_nodes
SET state = 'stale',
    failure = ?1,
    updated_at = ?2
WHERE id = ?3
  AND session_id = ?4
  AND algorithm_version = ?5
  AND state = 'active'
`

type StaleActiveContextProjectionNodeParams struct {
	Failure          string `json:"failure"`
	UpdatedAt        int64  `json:"updated_at"`
	ID               string `json:"id"`
	SessionID        string `json:"session_id"`
	AlgorithmVersion int64  `json:"algorithm_version"`
}

func (q *Queries) StaleActiveContextProjectionNode(ctx context.Context, arg StaleActiveContextProjectionNodeParams) (int64, error) {
	result, err := q.exec(ctx, q.staleActiveContextProjectionNodeStmt, staleActiveContextProjectionNode,
		arg.Failure,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
		arg.AlgorithmVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const staleContextProjectionClaim = `-- name: StaleContextProjectionClaim :execrows
UPDATE context_projection_nodes
SET state = 'stale',
    lease_expires_at = NULL,
    claim_token = NULL,
    retry_after = NULL,
    failure = ?1,
    summarizer_provider = ?2,
    summarizer_model = ?3,
    prompt_tokens = ?4,
    completion_tokens = ?5,
    cost = ?6,
    updated_at = ?7
WHERE id = ?8
  AND session_id = ?9
  AND algorithm_version = ?10
  AND state = 'pending'
  AND claim_token = ?11
`

type StaleContextProjectionClaimParams struct {
	Failure            string         `json:"failure"`
	SummarizerProvider string         `json:"summarizer_provider"`
	SummarizerModel    string         `json:"summarizer_model"`
	PromptTokens       int64          `json:"prompt_tokens"`
	CompletionTokens   int64          `json:"completion_tokens"`
	Cost               float64        `json:"cost"`
	UpdatedAt          int64          `json:"updated_at"`
	ID                 string         `json:"id"`
	SessionID          string         `json:"session_id"`
	AlgorithmVersion   int64          `json:"algorithm_version"`
	ClaimToken         sql.NullString `json:"claim_token"`
}

func (q *Queries) StaleContextProjectionClaim(ctx context.Context, arg StaleContextProjectionClaimParams) (int64, error) {
	result, err := q.exec(ctx, q.staleContextProjectionClaimStmt, staleContextProjectionClaim,
		arg.Failure,
		arg.SummarizerProvider,
		arg.SummarizerModel,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
		arg.AlgorithmVersion,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
