// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.accountContextProjectionUsageAttemptStmt, err = db.PrepareContext(ctx, accountContextProjectionUsageAttempt); err != nil {
		return nil, fmt.Errorf("error preparing query AccountContextProjectionUsageAttempt: %w", err)
	}
	if q.activateContextProjectionClaimStmt, err = db.PrepareContext(ctx, activateContextProjectionClaim); err != nil {
		return nil, fmt.Errorf("error preparing query ActivateContextProjectionClaim: %w", err)
	}
	if q.countContextProjectionItemsBySessionStmt, err = db.PrepareContext(ctx, countContextProjectionItemsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountContextProjectionItemsBySession: %w", err)
	}
	if q.countContextProjectionNodesBySessionStmt, err = db.PrepareContext(ctx, countContextProjectionNodesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountContextProjectionNodesBySession: %w", err)
	}
	if q.countContextProjectionSourcesBySessionStmt, err = db.PrepareContext(ctx, countContextProjectionSourcesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountContextProjectionSourcesBySession: %w", err)
	}
	if q.countContextProjectionUsageAttemptsBySessionStmt, err = db.PrepareContext(ctx, countContextProjectionUsageAttemptsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountContextProjectionUsageAttemptsBySession: %w", err)
	}
	if q.createContextProjectionClaimStmt, err = db.PrepareContext(ctx, createContextProjectionClaim); err != nil {
		return nil, fmt.Errorf("error preparing query CreateContextProjectionClaim: %w", err)
	}
	if q.createContextProjectionItemStmt, err = db.PrepareContext(ctx, createContextProjectionItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateContextProjectionItem: %w", err)
	}
	if q.createContextProjectionSourceStmt, err = db.PrepareContext(ctx, createContextProjectionSource); err != nil {
		return nil, fmt.Errorf("error preparing query CreateContextProjectionSource: %w", err)
	}
	if q.createContextProjectionUsageAttemptStmt, err = db.PrepareContext(ctx, createContextProjectionUsageAttempt); err != nil {
		return nil, fmt.Errorf("error preparing query CreateContextProjectionUsageAttempt: %w", err)
	}
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createMessageAtStmt, err = db.PrepareContext(ctx, createMessageAt); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessageAt: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteContextProjectionItemsByNodeStmt, err = db.PrepareContext(ctx, deleteContextProjectionItemsByNode); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteContextProjectionItemsByNode: %w", err)
	}
	if q.deleteContextProjectionSourcesByNodeStmt, err = db.PrepareContext(ctx, deleteContextProjectionSourcesByNode); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteContextProjectionSourcesByNode: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.failContextProjectionClaimStmt, err = db.PrepareContext(ctx, failContextProjectionClaim); err != nil {
		return nil, fmt.Errorf("error preparing query FailContextProjectionClaim: %w", err)
	}
	if q.getActiveContextProjectionItemByRefStmt, err = db.PrepareContext(ctx, getActiveContextProjectionItemByRef); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveContextProjectionItemByRef: %w", err)
	}
	if q.getActiveContextProjectionNodeForSourceStmt, err = db.PrepareContext(ctx, getActiveContextProjectionNodeForSource); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveContextProjectionNodeForSource: %w", err)
	}
	if q.getAverageResponseTimeStmt, err = db.PrepareContext(ctx, getAverageResponseTime); err != nil {
		return nil, fmt.Errorf("error preparing query GetAverageResponseTime: %w", err)
	}
	if q.getContextProjectionClaimStmt, err = db.PrepareContext(ctx, getContextProjectionClaim); err != nil {
		return nil, fmt.Errorf("error preparing query GetContextProjectionClaim: %w", err)
	}
	if q.getContextProjectionNodeStmt, err = db.PrepareContext(ctx, getContextProjectionNode); err != nil {
		return nil, fmt.Errorf("error preparing query GetContextProjectionNode: %w", err)
	}
	if q.getContextProjectionNodeForSourceStmt, err = db.PrepareContext(ctx, getContextProjectionNodeForSource); err != nil {
		return nil, fmt.Errorf("error preparing query GetContextProjectionNodeForSource: %w", err)
	}
	if q.getContextProjectionRefCounterStmt, err = db.PrepareContext(ctx, getContextProjectionRefCounter); err != nil {
		return nil, fmt.Errorf("error preparing query GetContextProjectionRefCounter: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getFileReadStmt, err = db.PrepareContext(ctx, getFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileRead: %w", err)
	}
	if q.getHourDayHeatmapStmt, err = db.PrepareContext(ctx, getHourDayHeatmap); err != nil {
		return nil, fmt.Errorf("error preparing query GetHourDayHeatmap: %w", err)
	}
	if q.getLastAssistantMessageBySessionStmt, err = db.PrepareContext(ctx, getLastAssistantMessageBySession); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastAssistantMessageBySession: %w", err)
	}
	if q.getLastSessionStmt, err = db.PrepareContext(ctx, getLastSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastSession: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getProjectionStatsStmt, err = db.PrepareContext(ctx, getProjectionStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetProjectionStats: %w", err)
	}
	if q.getRecentActivityStmt, err = db.PrepareContext(ctx, getRecentActivity); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentActivity: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getToolUsageStmt, err = db.PrepareContext(ctx, getToolUsage); err != nil {
		return nil, fmt.Errorf("error preparing query GetToolUsage: %w", err)
	}
	if q.getTotalStatsStmt, err = db.PrepareContext(ctx, getTotalStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalStats: %w", err)
	}
	if q.getUsageByDayStmt, err = db.PrepareContext(ctx, getUsageByDay); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDay: %w", err)
	}
	if q.getUsageByDayOfWeekStmt, err = db.PrepareContext(ctx, getUsageByDayOfWeek); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDayOfWeek: %w", err)
	}
	if q.getUsageByHourStmt, err = db.PrepareContext(ctx, getUsageByHour); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByHour: %w", err)
	}
	if q.getUsageByModelStmt, err = db.PrepareContext(ctx, getUsageByModel); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByModel: %w", err)
	}
	if q.listActiveContextProjectionNodesStmt, err = db.PrepareContext(ctx, listActiveContextProjectionNodes); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveContextProjectionNodes: %w", err)
	}
	if q.listActiveContextProjectionNodesBySourceMessageStmt, err = db.PrepareContext(ctx, listActiveContextProjectionNodesBySourceMessage); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveContextProjectionNodesBySourceMessage: %w", err)
	}
	if q.listAllActiveContextProjectionNodesBySessionStmt, err = db.PrepareContext(ctx, listAllActiveContextProjectionNodesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllActiveContextProjectionNodesBySession: %w", err)
	}
	if q.listAllUserMessagesStmt, err = db.PrepareContext(ctx, listAllUserMessages); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllUserMessages: %w", err)
	}
	if q.listCanonicalContextProjectionMessagesStmt, err = db.PrepareContext(ctx, listCanonicalContextProjectionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query ListCanonicalContextProjectionMessages: %w", err)
	}
	if q.listConflictingActiveContextProjectionNodesStmt, err = db.PrepareContext(ctx, listConflictingActiveContextProjectionNodes); err != nil {
		return nil, fmt.Errorf("error preparing query ListConflictingActiveContextProjectionNodes: %w", err)
	}
	if q.listContextProjectionItemsByNodeStmt, err = db.PrepareContext(ctx, listContextProjectionItemsByNode); err != nil {
		return nil, fmt.Errorf("error preparing query ListContextProjectionItemsByNode: %w", err)
	}
	if q.listContextProjectionSourcesByNodeStmt, err = db.PrepareContext(ctx, listContextProjectionSourcesByNode); err != nil {
		return nil, fmt.Errorf("error preparing query ListContextProjectionSourcesByNode: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listMessagesBySessionFromSummaryStmt, err = db.PrepareContext(ctx, listMessagesBySessionFromSummary); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySessionFromSummary: %w", err)
	}
	if q.listNewFilesStmt, err = db.PrepareContext(ctx, listNewFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListNewFiles: %w", err)
	}
	if q.listSessionReadFilesStmt, err = db.PrepareContext(ctx, listSessionReadFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionReadFiles: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listUnaccountedContextProjectionUsageStmt, err = db.PrepareContext(ctx, listUnaccountedContextProjectionUsage); err != nil {
		return nil, fmt.Errorf("error preparing query ListUnaccountedContextProjectionUsage: %w", err)
	}
	if q.listUserMessagesBySessionStmt, err = db.PrepareContext(ctx, listUserMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserMessagesBySession: %w", err)
	}
	if q.reclaimContextProjectionClaimStmt, err = db.PrepareContext(ctx, reclaimContextProjectionClaim); err != nil {
		return nil, fmt.Errorf("error preparing query ReclaimContextProjectionClaim: %w", err)
	}
	if q.recordFileReadStmt, err = db.PrepareContext(ctx, recordFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query RecordFileRead: %w", err)
	}
	if q.renameSessionStmt, err = db.PrepareContext(ctx, renameSession); err != nil {
		return nil, fmt.Errorf("error preparing query RenameSession: %w", err)
	}
	if q.reserveContextProjectionRefsStmt, err = db.PrepareContext(ctx, reserveContextProjectionRefs); err != nil {
		return nil, fmt.Errorf("error preparing query ReserveContextProjectionRefs: %w", err)
	}
	if q.setSessionChannelStmt, err = db.PrepareContext(ctx, setSessionChannel); err != nil {
		return nil, fmt.Errorf("error preparing query SetSessionChannel: %w", err)
	}
	if q.skipContextProjectionClaimStmt, err = db.PrepareContext(ctx, skipContextProjectionClaim); err != nil {
		return nil, fmt.Errorf("error preparing query SkipContextProjectionClaim: %w", err)
	}
	if q.staleActiveContextProjectionNodeStmt, err = db.PrepareContext(ctx, staleActiveContextProjectionNode); err != nil {
		return nil, fmt.Errorf("error preparing query StaleActiveContextProjectionNode: %w", err)
	}
	if q.staleContextProjectionClaimStmt, err = db.PrepareContext(ctx, staleContextProjectionClaim); err != nil {
		return nil, fmt.Errorf("error preparing query StaleContextProjectionClaim: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateSessionTitleAndUsageStmt, err = db.PrepareContext(ctx, updateSessionTitleAndUsage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionTitleAndUsage: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.accountContextProjectionUsageAttemptStmt != nil {
		if cerr := q.accountContextProjectionUsageAttemptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing accountContextProjectionUsageAttemptStmt: %w", cerr)
		}
	}
	if q.activateContextProjectionClaimStmt != nil {
		if cerr := q.activateContextProjectionClaimStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing activateContextProjectionClaimStmt: %w", cerr)
		}
	}
	if q.countContextProjectionItemsBySessionStmt != nil {
		if cerr := q.countContextProjectionItemsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countContextProjectionItemsBySessionStmt: %w", cerr)
		}
	}
	if q.countContextProjectionNodesBySessionStmt != nil {
		if cerr := q.countContextProjectionNodesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countContextProjectionNodesBySessionStmt: %w", cerr)
		}
	}
	if q.countContextProjectionSourcesBySessionStmt != nil {
		if cerr := q.countContextProjectionSourcesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countContextProjectionSourcesBySessionStmt: %w", cerr)
		}
	}
	if q.countContextProjectionUsageAttemptsBySessionStmt != nil {
		if cerr := q.countContextProjectionUsageAttemptsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countContextProjectionUsageAttemptsBySessionStmt: %w", cerr)
		}
	}
	if q.createContextProjectionClaimStmt != nil {
		if cerr := q.createContextProjectionClaimStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createContextProjectionClaimStmt: %w", cerr)
		}
	}
	if q.createContextProjectionItemStmt != nil {
		if cerr := q.createContextProjectionItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createContextProjectionItemStmt: %w", cerr)
		}
	}
	if q.createContextProjectionSourceStmt != nil {
		if cerr := q.createContextProjectionSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createContextProjectionSourceStmt: %w", cerr)
		}
	}
	if q.createContextProjectionUsageAttemptStmt != nil {
		if cerr := q.createContextProjectionUsageAttemptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createContextProjectionUsageAttemptStmt: %w", cerr)
		}
	}
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createMessageAtStmt != nil {
		if cerr := q.createMessageAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageAtStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteContextProjectionItemsByNodeStmt != nil {
		if cerr := q.deleteContextProjectionItemsByNodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteContextProjectionItemsByNodeStmt: %w", cerr)
		}
	}
	if q.deleteContextProjectionSourcesByNodeStmt != nil {
		if cerr := q.deleteContextProjectionSourcesByNodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteContextProjectionSourcesByNodeStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.failContextProjectionClaimStmt != nil {
		if cerr := q.failContextProjectionClaimStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing failContextProjectionClaimStmt: %w", cerr)
		}
	}
	if q.getActiveContextProjectionItemByRefStmt != nil {
		if cerr := q.getActiveContextProjectionItemByRefStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveContextProjectionItemByRefStmt: %w", cerr)
		}
	}
	if q.getActiveContextProjectionNodeForSourceStmt != nil {
		if cerr := q.getActiveContextProjectionNodeForSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveContextProjectionNodeForSourceStmt: %w", cerr)
		}
	}
	if q.getAverageResponseTimeStmt != nil {
		if cerr := q.getAverageResponseTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAverageResponseTimeStmt: %w", cerr)
		}
	}
	if q.getContextProjectionClaimStmt != nil {
		if cerr := q.getContextProjectionClaimStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getContextProjectionClaimStmt: %w", cerr)
		}
	}
	if q.getContextProjectionNodeStmt != nil {
		if cerr := q.getContextProjectionNodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getContextProjectionNodeStmt: %w", cerr)
		}
	}
	if q.getContextProjectionNodeForSourceStmt != nil {
		if cerr := q.getContextProjectionNodeForSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getContextProjectionNodeForSourceStmt: %w", cerr)
		}
	}
	if q.getContextProjectionRefCounterStmt != nil {
		if cerr := q.getContextProjectionRefCounterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getContextProjectionRefCounterStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getFileReadStmt != nil {
		if cerr := q.getFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileReadStmt: %w", cerr)
		}
	}
	if q.getHourDayHeatmapStmt != nil {
		if cerr := q.getHourDayHeatmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHourDayHeatmapStmt: %w", cerr)
		}
	}
	if q.getLastAssistantMessageBySessionStmt != nil {
		if cerr := q.getLastAssistantMessageBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastAssistantMessageBySessionStmt: %w", cerr)
		}
	}
	if q.getLastSessionStmt != nil {
		if cerr := q.getLastSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastSessionStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getProjectionStatsStmt != nil {
		if cerr := q.getProjectionStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectionStatsStmt: %w", cerr)
		}
	}
	if q.getRecentActivityStmt != nil {
		if cerr := q.getRecentActivityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentActivityStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getToolUsageStmt != nil {
		if cerr := q.getToolUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getToolUsageStmt: %w", cerr)
		}
	}
	if q.getTotalStatsStmt != nil {
		if cerr := q.getTotalStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalStatsStmt: %w", cerr)
		}
	}
	if q.getUsageByDayStmt != nil {
		if cerr := q.getUsageByDayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayStmt: %w", cerr)
		}
	}
	if q.getUsageByDayOfWeekStmt != nil {
		if cerr := q.getUsageByDayOfWeekStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayOfWeekStmt: %w", cerr)
		}
	}
	if q.getUsageByHourStmt != nil {
		if cerr := q.getUsageByHourStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByHourStmt: %w", cerr)
		}
	}
	if q.getUsageByModelStmt != nil {
		if cerr := q.getUsageByModelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByModelStmt: %w", cerr)
		}
	}
	if q.listActiveContextProjectionNodesStmt != nil {
		if cerr := q.listActiveContextProjectionNodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveContextProjectionNodesStmt: %w", cerr)
		}
	}
	if q.listActiveContextProjectionNodesBySourceMessageStmt != nil {
		if cerr := q.listActiveContextProjectionNodesBySourceMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveContextProjectionNodesBySourceMessageStmt: %w", cerr)
		}
	}
	if q.listAllActiveContextProjectionNodesBySessionStmt != nil {
		if cerr := q.listAllActiveContextProjectionNodesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllActiveContextProjectionNodesBySessionStmt: %w", cerr)
		}
	}
	if q.listAllUserMessagesStmt != nil {
		if cerr := q.listAllUserMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllUserMessagesStmt: %w", cerr)
		}
	}
	if q.listCanonicalContextProjectionMessagesStmt != nil {
		if cerr := q.listCanonicalContextProjectionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCanonicalContextProjectionMessagesStmt: %w", cerr)
		}
	}
	if q.listConflictingActiveContextProjectionNodesStmt != nil {
		if cerr := q.listConflictingActiveContextProjectionNodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listConflictingActiveContextProjectionNodesStmt: %w", cerr)
		}
	}
	if q.listContextProjectionItemsByNodeStmt != nil {
		if cerr := q.listContextProjectionItemsByNodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listContextProjectionItemsByNodeStmt: %w", cerr)
		}
	}
	if q.listContextProjectionSourcesByNodeStmt != nil {
		if cerr := q.listContextProjectionSourcesByNodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listContextProjectionSourcesByNodeStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionFromSummaryStmt != nil {
		if cerr := q.listMessagesBySessionFromSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionFromSummaryStmt: %w", cerr)
		}
	}
	if q.listNewFilesStmt != nil {
		if cerr := q.listNewFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNewFilesStmt: %w", cerr)
		}
	}
	if q.listSessionReadFilesStmt != nil {
		if cerr := q.listSessionReadFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionReadFilesStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listUnaccountedContextProjectionUsageStmt != nil {
		if cerr := q.listUnaccountedContextProjectionUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUnaccountedContextProjectionUsageStmt: %w", cerr)
		}
	}
	if q.listUserMessagesBySessionStmt != nil {
		if cerr := q.listUserMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.reclaimContextProjectionClaimStmt != nil {
		if cerr := q.reclaimContextProjectionClaimStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing reclaimContextProjectionClaimStmt: %w", cerr)
		}
	}
	if q.recordFileReadStmt != nil {
		if cerr := q.recordFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordFileReadStmt: %w", cerr)
		}
	}
	if q.renameSessionStmt != nil {
		if cerr := q.renameSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing renameSessionStmt: %w", cerr)
		}
	}
	if q.reserveContextProjectionRefsStmt != nil {
		if cerr := q.reserveContextProjectionRefsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing reserveContextProjectionRefsStmt: %w", cerr)
		}
	}
	if q.setSessionChannelStmt != nil {
		if cerr := q.setSessionChannelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setSessionChannelStmt: %w", cerr)
		}
	}
	if q.skipContextProjectionClaimStmt != nil {
		if cerr := q.skipContextProjectionClaimStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing skipContextProjectionClaimStmt: %w", cerr)
		}
	}
	if q.staleActiveContextProjectionNodeStmt != nil {
		if cerr := q.staleActiveContextProjectionNodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing staleActiveContextProjectionNodeStmt: %w", cerr)
		}
	}
	if q.staleContextProjectionClaimStmt != nil {
		if cerr := q.staleContextProjectionClaimStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing staleContextProjectionClaimStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateSessionTitleAndUsageStmt != nil {
		if cerr := q.updateSessionTitleAndUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionTitleAndUsageStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                                  DBTX
	tx                                                  *sql.Tx
	accountContextProjectionUsageAttemptStmt            *sql.Stmt
	activateContextProjectionClaimStmt                  *sql.Stmt
	countContextProjectionItemsBySessionStmt            *sql.Stmt
	countContextProjectionNodesBySessionStmt            *sql.Stmt
	countContextProjectionSourcesBySessionStmt          *sql.Stmt
	countContextProjectionUsageAttemptsBySessionStmt    *sql.Stmt
	createContextProjectionClaimStmt                    *sql.Stmt
	createContextProjectionItemStmt                     *sql.Stmt
	createContextProjectionSourceStmt                   *sql.Stmt
	createContextProjectionUsageAttemptStmt             *sql.Stmt
	createFileStmt                                      *sql.Stmt
	createMessageStmt                                   *sql.Stmt
	createMessageAtStmt                                 *sql.Stmt
	createSessionStmt                                   *sql.Stmt
	deleteContextProjectionItemsByNodeStmt              *sql.Stmt
	deleteContextProjectionSourcesByNodeStmt            *sql.Stmt
	deleteFileStmt                                      *sql.Stmt
	deleteMessageStmt                                   *sql.Stmt
	deleteSessionStmt                                   *sql.Stmt
	deleteSessionFilesStmt                              *sql.Stmt
	deleteSessionMessagesStmt                           *sql.Stmt
	failContextProjectionClaimStmt                      *sql.Stmt
	getActiveContextProjectionItemByRefStmt             *sql.Stmt
	getActiveContextProjectionNodeForSourceStmt         *sql.Stmt
	getAverageResponseTimeStmt                          *sql.Stmt
	getContextProjectionClaimStmt                       *sql.Stmt
	getContextProjectionNodeStmt                        *sql.Stmt
	getContextProjectionNodeForSourceStmt               *sql.Stmt
	getContextProjectionRefCounterStmt                  *sql.Stmt
	getFileStmt                                         *sql.Stmt
	getFileByPathAndSessionStmt                         *sql.Stmt
	getFileReadStmt                                     *sql.Stmt
	getHourDayHeatmapStmt                               *sql.Stmt
	getLastAssistantMessageBySessionStmt                *sql.Stmt
	getLastSessionStmt                                  *sql.Stmt
	getMessageStmt                                      *sql.Stmt
	getProjectionStatsStmt                              *sql.Stmt
	getRecentActivityStmt                               *sql.Stmt
	getSessionByIDStmt                                  *sql.Stmt
	getToolUsageStmt                                    *sql.Stmt
	getTotalStatsStmt                                   *sql.Stmt
	getUsageByDayStmt                                   *sql.Stmt
	getUsageByDayOfWeekStmt                             *sql.Stmt
	getUsageByHourStmt                                  *sql.Stmt
	getUsageByModelStmt                                 *sql.Stmt
	listActiveContextProjectionNodesStmt                *sql.Stmt
	listActiveContextProjectionNodesBySourceMessageStmt *sql.Stmt
	listAllActiveContextProjectionNodesBySessionStmt    *sql.Stmt
	listAllUserMessagesStmt                             *sql.Stmt
	listCanonicalContextProjectionMessagesStmt          *sql.Stmt
	listConflictingActiveContextProjectionNodesStmt     *sql.Stmt
	listContextProjectionItemsByNodeStmt                *sql.Stmt
	listContextProjectionSourcesByNodeStmt              *sql.Stmt
	listFilesByPathStmt                                 *sql.Stmt
	listFilesBySessionStmt                              *sql.Stmt
	listLatestSessionFilesStmt                          *sql.Stmt
	listMessagesBySessionStmt                           *sql.Stmt
	listMessagesBySessionFromSummaryStmt                *sql.Stmt
	listNewFilesStmt                                    *sql.Stmt
	listSessionReadFilesStmt                            *sql.Stmt
	listSessionsStmt                                    *sql.Stmt
	listUnaccountedContextProjectionUsageStmt           *sql.Stmt
	listUserMessagesBySessionStmt                       *sql.Stmt
	reclaimContextProjectionClaimStmt                   *sql.Stmt
	recordFileReadStmt                                  *sql.Stmt
	renameSessionStmt                                   *sql.Stmt
	reserveContextProjectionRefsStmt                    *sql.Stmt
	setSessionChannelStmt                               *sql.Stmt
	skipContextProjectionClaimStmt                      *sql.Stmt
	staleActiveContextProjectionNodeStmt                *sql.Stmt
	staleContextProjectionClaimStmt                     *sql.Stmt
	updateMessageStmt                                   *sql.Stmt
	updateSessionStmt                                   *sql.Stmt
	updateSessionTitleAndUsageStmt                      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                       tx,
		tx:                                       tx,
		accountContextProjectionUsageAttemptStmt: q.accountContextProjectionUsageAttemptStmt,
		activateContextProjectionClaimStmt:       q.activateContextProjectionClaimStmt,
		countContextProjectionItemsBySessionStmt: q.countContextProjectionItemsBySessionStmt,
		countContextProjectionNodesBySessionStmt: q.countContextProjectionNodesBySessionStmt,
		countContextProjectionSourcesBySessionStmt:          q.countContextProjectionSourcesBySessionStmt,
		countContextProjectionUsageAttemptsBySessionStmt:    q.countContextProjectionUsageAttemptsBySessionStmt,
		createContextProjectionClaimStmt:                    q.createContextProjectionClaimStmt,
		createContextProjectionItemStmt:                     q.createContextProjectionItemStmt,
		createContextProjectionSourceStmt:                   q.createContextProjectionSourceStmt,
		createContextProjectionUsageAttemptStmt:             q.createContextProjectionUsageAttemptStmt,
		createFileStmt:                                      q.createFileStmt,
		createMessageStmt:                                   q.createMessageStmt,
		createMessageAtStmt:                                 q.createMessageAtStmt,
		createSessionStmt:                                   q.createSessionStmt,
		deleteContextProjectionItemsByNodeStmt:              q.deleteContextProjectionItemsByNodeStmt,
		deleteContextProjectionSourcesByNodeStmt:            q.deleteContextProjectionSourcesByNodeStmt,
		deleteFileStmt:                                      q.deleteFileStmt,
		deleteMessageStmt:                                   q.deleteMessageStmt,
		deleteSessionStmt:                                   q.deleteSessionStmt,
		deleteSessionFilesStmt:                              q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:                           q.deleteSessionMessagesStmt,
		failContextProjectionClaimStmt:                      q.failContextProjectionClaimStmt,
		getActiveContextProjectionItemByRefStmt:             q.getActiveContextProjectionItemByRefStmt,
		getActiveContextProjectionNodeForSourceStmt:         q.getActiveContextProjectionNodeForSourceStmt,
		getAverageResponseTimeStmt:                          q.getAverageResponseTimeStmt,
		getContextProjectionClaimStmt:                       q.getContextProjectionClaimStmt,
		getContextProjectionNodeStmt:                        q.getContextProjectionNodeStmt,
		getContextProjectionNodeForSourceStmt:               q.getContextProjectionNodeForSourceStmt,
		getContextProjectionRefCounterStmt:                  q.getContextProjectionRefCounterStmt,
		getFileStmt:                                         q.getFileStmt,
		getFileByPathAndSessionStmt:                         q.getFileByPathAndSessionStmt,
		getFileReadStmt:                                     q.getFileReadStmt,
		getHourDayHeatmapStmt:                               q.getHourDayHeatmapStmt,
		getLastAssistantMessageBySessionStmt:                q.getLastAssistantMessageBySessionStmt,
		getLastSessionStmt:                                  q.getLastSessionStmt,
		getMessageStmt:                                      q.getMessageStmt,
		getProjectionStatsStmt:                              q.getProjectionStatsStmt,
		getRecentActivityStmt:                               q.getRecentActivityStmt,
		getSessionByIDStmt:                                  q.getSessionByIDStmt,
		getToolUsageStmt:                                    q.getToolUsageStmt,
		getTotalStatsStmt:                                   q.getTotalStatsStmt,
		getUsageByDayStmt:                                   q.getUsageByDayStmt,
		getUsageByDayOfWeekStmt:                             q.getUsageByDayOfWeekStmt,
		getUsageByHourStmt:                                  q.getUsageByHourStmt,
		getUsageByModelStmt:                                 q.getUsageByModelStmt,
		listActiveContextProjectionNodesStmt:                q.listActiveContextProjectionNodesStmt,
		listActiveContextProjectionNodesBySourceMessageStmt: q.listActiveContextProjectionNodesBySourceMessageStmt,
		listAllActiveContextProjectionNodesBySessionStmt:    q.listAllActiveContextProjectionNodesBySessionStmt,
		listAllUserMessagesStmt:                             q.listAllUserMessagesStmt,
		listCanonicalContextProjectionMessagesStmt:          q.listCanonicalContextProjectionMessagesStmt,
		listConflictingActiveContextProjectionNodesStmt:     q.listConflictingActiveContextProjectionNodesStmt,
		listContextProjectionItemsByNodeStmt:                q.listContextProjectionItemsByNodeStmt,
		listContextProjectionSourcesByNodeStmt:              q.listContextProjectionSourcesByNodeStmt,
		listFilesByPathStmt:                                 q.listFilesByPathStmt,
		listFilesBySessionStmt:                              q.listFilesBySessionStmt,
		listLatestSessionFilesStmt:                          q.listLatestSessionFilesStmt,
		listMessagesBySessionStmt:                           q.listMessagesBySessionStmt,
		listMessagesBySessionFromSummaryStmt:                q.listMessagesBySessionFromSummaryStmt,
		listNewFilesStmt:                                    q.listNewFilesStmt,
		listSessionReadFilesStmt:                            q.listSessionReadFilesStmt,
		listSessionsStmt:                                    q.listSessionsStmt,
		listUnaccountedContextProjectionUsageStmt:           q.listUnaccountedContextProjectionUsageStmt,
		listUserMessagesBySessionStmt:                       q.listUserMessagesBySessionStmt,
		reclaimContextProjectionClaimStmt:                   q.reclaimContextProjectionClaimStmt,
		recordFileReadStmt:                                  q.recordFileReadStmt,
		renameSessionStmt:                                   q.renameSessionStmt,
		reserveContextProjectionRefsStmt:                    q.reserveContextProjectionRefsStmt,
		setSessionChannelStmt:                               q.setSessionChannelStmt,
		skipContextProjectionClaimStmt:                      q.skipContextProjectionClaimStmt,
		staleActiveContextProjectionNodeStmt:                q.staleActiveContextProjectionNodeStmt,
		staleContextProjectionClaimStmt:                     q.staleContextProjectionClaimStmt,
		updateMessageStmt:                                   q.updateMessageStmt,
		updateSessionStmt:                                   q.updateSessionStmt,
		updateSessionTitleAndUsageStmt:                      q.updateSessionTitleAndUsageStmt,
	}
}
