// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AccountContextProjectionUsageAttempt(ctx context.Context, arg AccountContextProjectionUsageAttemptParams) (int64, error)
	ActivateContextProjectionClaim(ctx context.Context, arg ActivateContextProjectionClaimParams) (int64, error)
	CountContextProjectionItemsBySession(ctx context.Context, sessionID string) (int64, error)
	CountContextProjectionNodesBySession(ctx context.Context, sessionID string) (int64, error)
	CountContextProjectionSourcesBySession(ctx context.Context, sessionID string) (int64, error)
	CountContextProjectionUsageAttemptsBySession(ctx context.Context, sessionID string) (int64, error)
	CreateContextProjectionClaim(ctx context.Context, arg CreateContextProjectionClaimParams) (ContextProjectionNode, error)
	CreateContextProjectionItem(ctx context.Context, arg CreateContextProjectionItemParams) error
	CreateContextProjectionSource(ctx context.Context, arg CreateContextProjectionSourceParams) error
	CreateContextProjectionUsageAttempt(ctx context.Context, arg CreateContextProjectionUsageAttemptParams) error
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMessageAt(ctx context.Context, arg CreateMessageAtParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteContextProjectionItemsByNode(ctx context.Context, nodeID string) error
	DeleteContextProjectionSourcesByNode(ctx context.Context, nodeID string) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	FailContextProjectionClaim(ctx context.Context, arg FailContextProjectionClaimParams) (int64, error)
	GetActiveContextProjectionItemByRef(ctx context.Context, arg GetActiveContextProjectionItemByRefParams) (ContextProjectionItem, error)
	GetActiveContextProjectionNodeForSource(ctx context.Context, arg GetActiveContextProjectionNodeForSourceParams) (ContextProjectionNode, error)
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetContextProjectionClaim(ctx context.Context, arg GetContextProjectionClaimParams) (ContextProjectionNode, error)
	GetContextProjectionNode(ctx context.Context, arg GetContextProjectionNodeParams) (ContextProjectionNode, error)
	GetContextProjectionNodeForSource(ctx context.Context, arg GetContextProjectionNodeForSourceParams) (ContextProjectionNode, error)
	GetContextProjectionRefCounter(ctx context.Context) (int64, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastAssistantMessageBySession(ctx context.Context, sessionID string) (Message, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetProjectionStats(ctx context.Context) (GetProjectionStatsRow, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	ListActiveContextProjectionNodes(ctx context.Context, arg ListActiveContextProjectionNodesParams) ([]ContextProjectionNode, error)
	ListActiveContextProjectionNodesBySourceMessage(ctx context.Context, arg ListActiveContextProjectionNodesBySourceMessageParams) ([]ContextProjectionNode, error)
	ListAllActiveContextProjectionNodesBySession(ctx context.Context, sessionID string) ([]ContextProjectionNode, error)
	// Backs prompt history when no session is open. Needs
	// idx_messages_role_created_at to seek rather than scan the table.
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListCanonicalContextProjectionMessages(ctx context.Context, sessionID string) ([]Message, error)
	ListConflictingActiveContextProjectionNodes(ctx context.Context, arg ListConflictingActiveContextProjectionNodesParams) ([]ContextProjectionNode, error)
	ListContextProjectionItemsByNode(ctx context.Context, nodeID string) ([]ContextProjectionItem, error)
	ListContextProjectionSourcesByNode(ctx context.Context, nodeID string) ([]ContextProjectionSource, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// Messages from the summary onward, which is all a compacted session sends.
	// created_at has one-second resolution, so a few messages preceding the
	// summary can come back too; the caller slices from the summary by ID.
	ListMessagesBySessionFromSummary(ctx context.Context, arg ListMessagesBySessionFromSummaryParams) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListUnaccountedContextProjectionUsage(ctx context.Context, sessionID string) ([]ContextProjectionUsageAttempt, error)
	// Backs prompt history, which steps back one entry at a time.
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ReclaimContextProjectionClaim(ctx context.Context, arg ReclaimContextProjectionClaimParams) (ContextProjectionNode, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	ReserveContextProjectionRefs(ctx context.Context, count int64) (int64, error)
	SetSessionChannel(ctx context.Context, arg SetSessionChannelParams) (Session, error)
	SkipContextProjectionClaim(ctx context.Context, arg SkipContextProjectionClaimParams) (int64, error)
	StaleActiveContextProjectionNode(ctx context.Context, arg StaleActiveContextProjectionNodeParams) (int64, error)
	StaleContextProjectionClaim(ctx context.Context, arg StaleContextProjectionClaimParams) (int64, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
}

var _ Querier = (*Queries)(nil)
